### PR TITLE
Hide button

### PR DESCRIPTION
**Pull request by Eskaan**
Added a button to hide the launcher like the minimize button on Windows does. Linux and MacOS are handling this an other way.

### CODE REVIEW

**Comment by Eskaan** [comment]
grafik

**Comment by blarfoon** [comment]
ummh, do we really want this? Do other apps have a button like that?

**Comment by Mari023** [comment]
Discord has an option to replace the close button with an hide button, twitch has one too
skype, slack, jetbrains toolbox and steam also do this with the close button

tl,dr: most apps just use the close button for this functionality

**Comment by Eskaan** [comment]
> Discord has an option to replace the close button with an hide button, twitch has one too
> skype, slack, jetbrains toolbox and steam also do this with the close button
> 
> tl,dr: most apps just use the close button for this functionality

will add an option whether to quit or hide when clicking on the close button. Thanks, thats a way better way to do this :D

**Comment by blarfoon** [comment]
up

**Comment by Eskaan** [comment]
> up

Currently working on other things (-> Java draft)

**Pull request closed without merging**
