### PR TITLE
Fixed feature request template typo

### PR DESCRIPTION
**Pull request by rlnt**

### CODE REVIEW

**Comment by AzureDoom** [comment]
Please note the master branch is not supported anymore. All work is focused on the next branch to get it ready

**Comment by rlnt** [comment]
Good to know. Closed.

**Comment by furtabs** [comment]
@AzureDoom No your wrong this is for the Feature Requests issue template that goes into master. Sorry about that.

**Comment by AzureDoom** [comment]
Ah, I just saw it was the for the master branch. Sorry @CrankySupertoon

**Pull request closed without merging**
