### PR TITLE
Cache

### LINKED ISSUE #424: [Feature] Cache mods in GDLauncher so if another modpack has the same mod with the same checksum it wont redownload it and use the cached one
### We are currently only taking Feature Requests for the Upcoming Next Release which will fix most of the legacy build's bugs.
---

**Describe the new feature you are requesting**
A way to toggle an ability to save mods jars in a cache folder so any modpacks that have x mod will use the cached one instead.

**Describe alternatives to this feature if Applicable**
Cant think of any

**Additional Inforomation**

### PR DESCRIPTION
**Pull request by TOLoneWolf**
To speed up installing the same versions:
- Checks if vanilla version was downloaded, skipping asset download if it was.
- Checks if forge version was already downloaded and patched, skipping asset download and patch if it was.

Added mod caching using existing instance as the cache source.

Added "categorySection.path". This is required for correct destination of curseforge file (mod, resourcepack, world save). This fixes modpacks containing resource packs.
Example:
Modpack with resource pack for testing changing destination of downloaded curseforge files.
HR: New Beginnings version: New Beginnings-1.2.1.zip
https://www.curseforge.com/minecraft/modpacks/hr-new-beginnings/files/2908388

texturepack(resourcepack): Fancy Skies

### CODE REVIEW

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/reducers/actions.js  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5561882&bid=18239767)

**Comment by blarfoon** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/reducers/actions.js  8
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5561882&bid=18239767)

**Comment by blarfoon** [comment]
I don't really like checking for the json to download forge stuff. If for any reason the json is still there but any of the forge files is deleted/corrupted, it will never download it again. I personally think it's better to check for specific things right before downloading them

**Comment by TOLoneWolf** [comment]
https://github.com/gorilla-devs/GDLauncher/pull/429

https://github.com/gorilla-devs/GDLauncher/pull/429#issuecomment-626029313

**Pull request closed without merging**
