### PR TITLE
Add technic modpacks

### PR DESCRIPTION
**Pull request by jetocotoje**
## Purpose
This PR adds support for technicpack (both legacy and solder API) modpacks.
Linked issue: #109 

## Approach
I have added API calls to technic and solder for fetching modpack information and created modpack views + actions for solder and technic modpacks.
Unfortunately, legacy API only supports the latest version and both APIs do not return any specifically version-related timestamps to use as release dates.

#### Open Questions and Pre-Merge TODOs
- [ ] Is there a better way for handling one-zip modpacks?
- [ ] Most of the time, no information about required forge versions is returned, should this be scraped from version.json inside modpack.jar or left at the latest fml version?

## Learning
* Used API documentation for [Technic](https://technicapi.docs.apiary.io/#/) and [Solder](https://docs.solder.io/docs/api)
* Sniffed a working build version for the API from Technic Launcher, since the [update endpoint](
https://api.technicpack.net/launcher/version/) returns outdated data.

### CODE REVIEW

**Comment by Eskaan** [comment]
@killpowa how about a review?

**Comment by mind-overflow** [comment]
Still no update on this?

**Comment by Eskaan** [comment]
Nope. No review no merge.

**Comment by blarfoon** [comment]
Hi guys, sorry this took so long. This PR is good but there are a few issues. First of all, there are some conflicts I would like to see resolved. Moreover, I found these issues.

Tekkit latest version downloads fine but fails to run:
image

Hexxit latest fails to download because of a 404 error:
image

Hexxit II has a mod issue:
image

When exploring versions for a modpack all dates are invalid:
image

I would love to merge this PR as soon as these issues are fixed. Feel free to hop in our discord server if you need help with this or you want to discuss about it.

**Comment by mind-overflow** [comment]
@killpowa thank you for the report! This is not my PR but I can definitely take a look if @KundaPanda is either busy or not interested anymore. It feels weird that there are so many issues now though - I'd think that he tried a build before submitting the request. Could the API have changed yet again?

**Comment by blarfoon** [comment]
I am not sure but feel free to pick this PR up and contact me on discord to discuss the details

**Pull request closed without merging**
