### PR TITLE
Adjust size of scrollbar and move it away from the resizer region

### PR DESCRIPTION
**Pull request by YoYoK3nny**
## Purpose
To fix issue #1104.

## Approach
Make the scrollbar slightly larger and add a small margin on the right side of the Settings modal.

### CODE REVIEW

**Comment by Eskaan** [comment]
Seems  good to me, will approve it when I tested it. :)

**Comment by huantianad** [comment]
We should also consider physically making the scrollbar wider, with something like
```css
::-webkit-scrollbar {
    width: 12px;  /* Change this as appropriate */
}
```
We would then also need to move some UI elements appropriately

**Comment by YoYoK3nny** [comment]
> We should also consider physically making the scrollbar wider, with something like
> 
> ```css
> ::-webkit-scrollbar {
>     width: 12px;  /* Change this as appropriate */
> }
> ```
> 
> We would then also need to move some UI elements appropriately

While I agree (on behalf of those with difficulties using small UI elements), I believe those changes would be better done as adding support for custom UI themes.

**Comment by huantianad** [comment]
I think UI Themes would be cool, but that should be discussed seperately, I think a wider scrollbar is just a basic feature that should be implemented anyways

**Comment by YoYoK3nny** [comment]
> I think UI Themes would be cool, but that should be discussed seperately,

They would be cool, and have been discussed separately more than once in one form or another already, so I won't be adding another.

>  I think a wider scrollbar is just a basic feature that should be implemented anyways

I agree, but also something to be discussed separately, this PR is meant to make the currently implemented size work as expected via mouse click.

**Review by Eskaan — CHANGES_REQUESTED** [review]
Isn’t 12px as big as usual Windows scroolbars?
Would take something smaller for MacOS because we only have like ~5px scroolbars. Also is this tested? I didn’t test it by now but I guess the scroolbar is still Same size and only the side moved way to the side

**Comment by YoYoK3nny** [comment]
> Isn’t 12px as big as usual Windows scroolbars? Would take something smaller for MacOS because we only have like ~5px scroolbars. Also is this tested? I didn’t test it by now but I guess the scroolbar is still Same size and only the side moved way to the side

Scrollbar is indeed the same size. I am unable to test as I don't have a suitable dev environment (npm fails to install the dependencies on my Windows machine) and I couldn't find where to make the change inside the app.asar file.
The research that I did, prior to making the PR, suggested that where I added the smaller padding should work.

EDIT: After fiddling using the Developer Tools, that may not be the right spot, so maybe widening the scrollbar is the better option for now. Will continue to search for the right spot.

**Comment by YoYoK3nny** [comment]
This should be a better solution now.

Changes are:

- Scrollbar size is now 6 pixels.
- Settings modal has a 3 pixel margin on the right side to move the scrollbar out of the resizer region.

Changes tested using the built-in Developer Tools. ~1-2 pixels are still affected by the resizer region.

**Comment by blarfoon** [comment]
This will be addressed very similarly in a upcoming release, I appreciate the PR anyway

**Pull request closed without merging**
