### PR TITLE
Being able to launch other versions of Minecraft

### PR DESCRIPTION
**Pull request by zKyros**
## Purpose
_Being able to install alternative Minecraft versions_
## Approach
_Would be nice to have a category of Minecraft releases called “Others” where users can put the version folder they want to use in to be able to launch it, for example you can do this by programming the launcher to show the releases added in an X folder in the same folder where GDLauncher puts the Minecraft versions files_

PS: I’ve never used GitHub so maybe the Pull has some problems. In case make me know it!

### CODE REVIEW

**Comment by zKyros** [comment]
Nobody is interested to that?

**Comment by KirillUva** [comment]
Its such an awesome idea! Just like Tlauncher, you can make modpacks with your own names and versions!

**Review by KirillUva — APPROVED** [review]
I think this would be an amazing idea @zKyros. Try to send a message on the discord server, you may get an answer there.

**Comment by blarfoon** [comment]
Please open an issue for this

**Pull request closed without merging**
