### PR TITLE
 restyled remote mods list

### PR DESCRIPTION
**Pull request by Ladvace**

### CODE REVIEW

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/common/modals/ModsBrowser.js  -3
         

Clones added
============
- src/common/modals/ModsBrowser.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6132155&bid=20054901)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/common/modals/ModsBrowser.js  -3
         

Clones added
============
- src/common/modals/ModsBrowser.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6132155&bid=20054901)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/common/modals/ModsBrowser.js  -3
         

Clones added
============
- src/common/modals/ModsBrowser.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6132155&bid=20054901)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/common/modals/ModsBrowser.js  -3
         

Clones added
============
- src/common/modals/ModsBrowser.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6132155&bid=20054901)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ src/common/modals/ModsBrowser.js  -3
         

Clones added
============
- src/common/modals/ModsBrowser.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6132155&bid=20054901)

**Comment by blarfoon** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/ModsBrowser.js  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6132155&bid=20054901)

**Pull request closed without merging**
