### PR TITLE
Add architecture-dependend metadata

### PR DESCRIPTION
**Pull request by Eskaan**
This should finish up with the Launcher supporting Arch. Thanks for providing the sources @theofficialgman.

### CODE REVIEW

**Comment by theofficialgman** [comment]
keep in mind that these are linux arm32 and linux arm64 only repos.
everything else is stripped from them (no windows x86, x86_64, arm64 or macos x64, arm64)

I think process.arch is a runtime switch. I am not sure if macos ARM64 running an x86_64 electron app will return arm64 or x64 but you need it to return x64 otherwise it will point to my repos which simply won't work on macos

just run process.arch in an electron x86_64 application's debug terminal (whatever it is called) on an apple silicon mac to test

**Comment by Eskaan** [comment]
That's simple. If you try running a arm64 or just arm app on x64, it will just fail with an execFormatError. The formats are not compatible. I don't think we support mac silicon yet.

**Comment by theofficialgman** [comment]
> That's simple. If you try running a arm64 or just arm app on x64, it will just fail with an execFormatError. The formats are not compatible. I don't think we support mac silicon yet.

umm no
macos has rosetta2 which allows running x64 apps on arm64 without any code or binay changes. they "just work" and the developer doesn't control what users run. gdlauncher I'm sure already works (with java x64 and x64 natives) all running through the rosetta2 translation layer.

**Comment by Eskaan** [comment]
@theofficialgman update on your thoughts: I let @killpowa check on his silicon mac that everything works. I think our binaries are compiled against x64 macos and thus the `process.arch` is x64. We released a beta btw.

**Pull request merged**
