### PR TITLE
Add Quilt Support

### LINKED ISSUE #1308: Quilt support
Hello! I'm a Community Manager and member of the Outreach Team over at [The Quilt Project](https://quiltmc.org).

Quilt is a new Minecraft mod-loader, which builds upon the technical foundations of Fabric but takes a different approach to governance and development, among other improvements.

This may, of course, be _way_ too early to be bringing this up - Quilt reaches its first beta release on the 20th of April (6 days from this issue) - but I wanted to get the ball rolling: If you've heard of us, are there any plans to support Quilt in GDLauncher? If not, what does it take to bring a new mod-loader to GDLauncher?

Technically-speaking, launcher support for Quilt is quite similar to Fabric, but our dev team is always happy to help out with the finer details.

Thanks in advance!

### PR DESCRIPTION
**Pull request by Ecorous**
## Purpose
_Describe the problem or feature in addition to a link to the issues when possible._
Adds Quilt Support to the launcher 
Closes #1308 

## Approach
_How does this change address the problem?_
Adds QuiltMC support

#### Open Questions and Pre-Merge TODOs
- [x] Add base
- [x] Actually launch Quilt
- [ ] Fix mod manager

### CODE REVIEW

**Comment by Hedwig7s** [comment]
_Continues waiting impatiently_

**Comment by Eskaan** [comment]
@Hedwig7s this is an Open Source project. We are all volunteers and leaving unhelpful messages on multiple issues/prs isn't really helpful.

**Comment by Hedwig7s** [comment]
> @Hedwig7s this is an Open Source project. We are all volunteers and leaving unhelpful messages on multiple issues/prs isn't really helpful.

Proceeds to still wait impatiently
Hey a milestone was hit at least

**Moderator edit**
Following messages like this will be deleted. Do it on your own if you're so impatient.

**Comment by Ecorous** [comment]
> > @Hedwig7s this is an Open Source project. We are all volunteers and leaving unhelpful messages on multiple issues/prs isn't really helpful.
> 
> Proceeds to still wait impatiently Hey a milestone was hit at least
> 
> **Moderator edit** Following messages like this will be deleted. Do it on your own if you're so impatient.

Personally, @Hedwig7s, I'm getting quite annoyed with you. Developing is hard, and you're criticizing the speed at which I contribute **out of my free time** to an open source project. I have a life outside of developing, and with that comes responsibilities. This means that I do spend a lot of my free time on this, but my free time is still limited.

**Comment by CapoFantasma97** [comment]
Perhaps it could be useful to also have a filter for the mod manager (CurseForge and in the future Modrinth) to choose whether to show Quilt only or all compatible (therefore including Fabric) mods.

Low priority but I would find it interesting. Some mods work better in their Quilt version, a few others are Quilt only, so it would come in handy.

**Comment by HarvelsX** [comment]
It doesn't seem to work if you add any modification. 
Quilt Loader refuses to create a remapped Jar game.

**UPD**
`org\quiltmc\hashed\1.19.2\hashed-1.19.2.jar` crashes the boot if run with the same arguments from the command line
now it cannot get OpenGL information WTF

**Comment by Ecorous** [comment]
> It doesn't seem to work if you add any modification. Quilt Loader refuses to create a remapped Jar game.

Huh, I haven't worked on this for a while, but I'll have a look at some point

**Comment by AshtakaOOf** [comment]
It's been a while, has anything happened?

**Comment by CapoFantasma97** [comment]
> It's been a while, has anything happened?

Haven't you noticed there's an entire rewrite of the whole app in the works, and the partnership with CurseForge? Lmao

**Comment by AshtakaOOf** [comment]
> Haven't you noticed there's an entire rewrite of the whole app in the works, and the partnership with CurseForge? Lmao

I am well aware of that. The rewrite is far and I mean really far from being production ready.
I am just checking in to know how Ecorous is doing, since it has been 3 months since his last comment on this PR.
edit: What I previously said was a bit too aggressive and i explained why i made this comment

**Comment by CapoFantasma97** [comment]
> > Haven't you noticed there's an entire rewrite of the whole app in the works, and the partnership with CurseForge? Lmao
> 
> I am well aware of that. The rewrite is far and I mean really far from being production ready.
> I am just checking in to know how Ecorous is doing, since it has been 3 months since his last comment on this PR.
> edit: What I previously said was a bit too aggressive and i explained why i made this comment

What I left implicit is that, like mentioned in the website, the current launcher is getting gradually discontinued in favor of working on the rewrite, therefore new features such as Quilt support will be addressed by the new launcher.

Davide, the founder, also mentioned in the Discord server that Quilt support will not be added to the current launcher.

**Comment by Ecorous** [comment]
> > Haven't you noticed there's an entire rewrite of the whole app in the works, and the partnership with CurseForge? Lmao
> 
> I am well aware of that. The rewrite is far and I mean really far from being production ready. I am just checking in to know how Ecorous is doing, since it has been 3 months since his last comment on this PR. edit: What I previously said was a bit too aggressive and i explained why i made this comment

`his`. Also, no, I haven't had any time to work on this

**Comment by AshtakaOOf** [comment]
> Davide, the founder, also mentioned in the Discord server that Quilt support will not be added to the current launcher.

He won't add support for it himself, but if someone was or is willing to do it they were free to do so.

**Comment by Ecorous** [comment]
I'm retracting my contribution to the project.

**Pull request closed without merging**
