### PR TITLE
Fix curse forge download

### PR DESCRIPTION
**Pull request by LuqDragon**
## Purpose
Solve the problem with CurseForge download without manual downloads and anothers workarounds.
Was tested in #1342, #1357 and from CurseForge menu, and worked just fine.

## Approach
This solve the problem creating a URL based on what comes in `manifest.json` files from CurseForge.

## Learning

The composition of the URL is: 
`https://edge.forgecdn.net/files/[first 4 numbers from manifest id]/[rest of the numbers of manifest id]/[file name]`

Samples:
<https://edge.forgecdn.net/files/3723/913/jei-1.18.2-9.5.5.174.jar>
<https://edge.forgecdn.net/files/3734/559/jei-1.18.2-9.6.0.179.jar>
### *This is a sample, didn't yet apply to all the paths*

### CODE REVIEW

**Comment by DioEgizio** [comment]
This breaks the CurseForge Core 3rd Party API Terms and Conditions

**Comment by blarfoon** [comment]
As @DioEgizio said, this PR violates CF's TOS so even though this might technically be the best solution, we won't be able to integrate it into the launcher.

**Comment by LuqDragon** [comment]
Ok so, I wonder how others launchers are handle this tough

**Comment by DioEgizio** [comment]
Like #1356/#1345

**Comment by LuqDragon** [comment]
FTB App download automatically from CurseForge, it have a way to do it instead manually access the site and click buttons, thats my question

**Comment by DioEgizio** [comment]
No, FTB has an agreement with CurseForge, in fact that's why they need to show ads and use the overwolf platform

**Comment by LuqDragon** [comment]
I understood

**Pull request closed without merging**
