### PR TITLE
Portable Builds

### PR DESCRIPTION
**Pull request by furtabs**

### CODE REVIEW

**Comment by blarfoon** [comment]
Zip builds do not come with auto updates. We need to think about an auto update system for them before releasing

**Comment by furtabs** [comment]
Does it look like we care about auto updates. The app image doesn’t auto update either. People want portable builds, and Mac already has a portable option

**Comment by kreezxil** [comment]
have an option in the installer that asks them if that want a portable
install? if they select yes, then they can select another folder to put it.

**Comment by furtabs** [comment]
@kreezxil that doesnt fix the linux issue. i just want the app image gone

**Pull request closed without merging**
