### PR TITLE
Add option for Curseforge API key, Add Third Party Launcher Notice

### LINKED ISSUE #1342: Instance Download Failed, The url argument must be of type string
**Describe the bug**
When installing [this modpack](https://oitsjustjose-sharex.s3.us-east-2.amazonaws.com/2022/05/ForgeServ-6.0.1.zip), I receive the error:

```log
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received null
```

**To Reproduce**
1. Download the modpack export from above, and import it
2. After the Forge install succeeds, wait for the failure popup

**Expected behavior**
The pack update works fine

**Possible solutions**
No ideas honestly, I'm dumbfounded

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Operating System:**
- OS: Windows
- Version: 11
- Java Version: 17
- Minecraft Version: 1.18.2
- Mod Loader: Forge

**Additional context**

GDLauncher Version 1.1.23.

You can also install from CurseForge to receive the same failure -- [this version](https://www.curseforge.com/minecraft/modpacks/forgeserv/files/3794746) of the modpack installed just fine on Tuesday 5/17, and today won't install.

### PR DESCRIPTION
**Pull request by oitsjustjose**
## Purpose

Some users may be able to use the CF Core API to use their own API keys or may want to test out making their own application key. Due to the recent changes in the CurseForge API, the ability to define your own API key if desired would be nice - as seen in other launchers, this advanced option handles this nicely.

## Approach

The default GDLauncher key is used by default, but under a new *Experimental* tab in the settings modal, the user can provide their own after reading an in-depth explanation as to what is the purpose of this key. If they tamper with it and cause the API calls to fail, they can easily reset this option in the UI.

Additionally, a new dismissable notification has been added to notify the user that if their download fails, this is due to the recent CurseForge API changes.

#### Showcase

[Watch the video](https://oitsjustjose-sharex.s3.us-east-2.amazonaws.com/2022/06/06-11-22%2009-56-32-736.mp4)

#### Other Notes

I know that CurseForge API stuff is highly controversial and highly volatile at the moment. That said, absolutely **anyone** can go to [https://console.curseforge.com/#/api-keys](https://console.curseforge.com/#/api-keys) and get their own API key to use. If anything, this is a *good* thing for CF because it means individual users can get their own keys, thus granting CF the ability to gather analytics on what user is downloading what kinds of content. All of this can be done without breaching any of Curse's TOS as far as I understand.

Furthermore, this PR serves as proof that I, oitsjustjose, am solely responsible for this change so if CF have an issue with this change it can be easily reverted and the blame can lie on me and me alone.

### CODE REVIEW

**Comment by oitsjustjose** [comment]
This would be a good final resolution for https://github.com/gorilla-devs/GDLauncher/issues/1342, closing it on the grounds that literally nothing more can be done on GDL's end but how they choose to use this API key option is entirely up to them.

**Comment by oitsjustjose** [comment]
Just added in a nice modal for which files failed to download:

**Comment by SirOMGitsYOU** [comment]
I like this, maybe it would only be helpful to a handful of people but hey if it's an easy implementation option I think it would be a really sweet option to have as for the opted-out files it would be really nice to maybe see this PR and https://github.com/gorilla-devs/GDLauncher/pull/1345 combined as Ladvace has done a great option for downloading mods that have been opted-out by popping up a browser window!

**Comment by oitsjustjose** [comment]
Cleaned up the mod list failure, and also changed the way the axios api header was getting grabbed, using a Redux subscriber instead of hot glue and dreams.

The new failed downloads list:

**Comment by AshtakaOOf** [comment]
I just want to report a typo error. Here is the error

**Comment by AshtakaOOf** [comment]
Also if you could help on this [Pull request](https://github.com/gorilla-devs/GDLauncher/pull/1345) that is almost merged in to the main branch.
Also do not hesitate to join the [discord server](https://discord.com/invite/3WjYJTBcSz) if you want to talk to the devs there.

**Comment by Eskaan** [comment]
I still see this pr as a good long term solution as the CF API breaks regularly

**Comment by SirOMGitsYOU** [comment]
> I still see this pr as a good long term solution as the CF API breaks regularly

I think having users get their own API if an issue with the default API key happens then it would help alleviate any issues on the main API usage

**Comment by oitsjustjose** [comment]
I've gone through and removed the code which was redundant with #1345

**Comment by oitsjustjose** [comment]
As such, with the wonderful changes in #1345 does anyone feel the need to keep the dismissable notice about needing to download mods manually, seeing as you usually will not need to?

**Comment by AshtakaOOf** [comment]
I think you could change it, like if it fails a download it appears and explain some solution and why it failed.

**Comment by oitsjustjose** [comment]
Done - should be good for review now? 🤞

**Comment by blarfoon** [comment]
I personally dislike the additional warning message, especially since it doesn't come from our APIs but is rather hardcoded. Could you remove it?
Also, opted-out mods download has been already addressed in https://github.com/gorilla-devs/GDLauncher/pull/1345 so I think you can remove that as well.

**Comment by oitsjustjose** [comment]
> I personally dislike the additional warning message, especially since it doesn't come from our APIs but is rather hardcoded. Could you remove it?

Sure, done in bf21848

> Also, opted-out mods download has been already addressed in #1345 so I think you can remove that as well.

Removed in 8b3ca5f82fea394378dd3a0f9a565c5dab82cc50

**Comment by oitsjustjose** [comment]
CLA *should* be signed, not sure why it hasn't caught that yet.

**Comment by oitsjustjose** [comment]
@killpowa I didn't see any explanation for this being closed w/o merge, just curious if there was one? NBD if there wasn't really a reason.

**Comment by SirOMGitsYOU** [comment]
> @killpowa I didn't see any explanation for this being closed w/o merge, just curious if there was one? NBD if there wasn't really a reason.

I think it was closed as part of the GitHub history cleanup may be worth re-opening a new PR like the Modrinth PR has done.

**Comment by Hedwig7s** [comment]
@oitsjustjose Still recommend doing that

**Pull request closed without merging**
