### PR TITLE
Launch instance from cli to allow desktop shortcuts etc.

### LINKED ISSUE #409: [Feature] Ability to change launcher colour scheme
The old launcher had the ability to change the colour scheme.  I really enjoyed that feature and would like to see it again, it made the launcher more personal. Exactly how it was before was great.

### PR DESCRIPTION
**Pull request by olechiw**
## Purpose
_Describe the problem or feature in addition to a link to the issues when possible._
Add ability to create desktop shortcuts that immediately launch an instance

## Approach
_How does this change address the problem?_
Add the ability to specify an instance to launch on startup for GDLauncher with `--instance=instance_name` i.e. `--instance=Omnifactory`

I have never used redux but the idea here was to set a flag `hasStartedCliInstance` so that if the instances component reloads it doesn't attempt to launch again for the lifetime of the app.

### CODE REVIEW

**Comment by kirjorjos** [comment]
This is now working on my Linux Mint install perfectly, my use case being starting a pack on system startup as well as the desktop shortcuts mentioned above.

**Comment by SiegfredRodriguez** [comment]
Hello @killpowa,
What happened to this feature? 
Was it merged?

**Comment by Eskaan** [comment]
Sadly this was not merged. I think it is not denied and would be considered if rebased.

**Comment by kirjorjos** [comment]
I'm aware I'm most likely an exception, but as of right now, this is the one feature missing that turns me away from GD launcher.

**Pull request closed without merging**
