### PR TITLE
Remove Symlink option for non-Windows

### PR DESCRIPTION
**Pull request by Eskaan**
Defaults to not-symlink so we are going no change no problem here ;) 
see also Commit Message

### CODE REVIEW

**Review by blarfoon — CHANGES_REQUESTED** [review]
You should not disable the setting completely but just disable the `<Select.Option` option

**Comment by Eskaan** [comment]
But what sense would that make to have a non changeable setting?

**Comment by blarfoon** [comment]
None but it's for consistency.

**Comment by Eskaan** [comment]
Well review it again in 5 sec Edit Minutes I mean 😅

**Comment by Eskaan** [comment]
Yes, the force push was justified for me because there is basically no work in this branch and you will be able to still rebase like this. @killpowa *review requested*

**Comment by Eskaan** [comment]
Aaah wont work I think
One sec need to get the dev env running

**Comment by blarfoon** [comment]
This hides the option, doesn't disable it lul

**Comment by Eskaan** [comment]
> This hides the option, doesn't disable it lul

Aaah so that’s what you want. That is even easier lol

**Review by blarfoon — APPROVED** [review]

**Pull request merged**
