### PR TITLE
Orange CF Logo

### PR DESCRIPTION
**Pull request by Ecorous**
## Purpose
_Describe the problem or feature in addition to a link to the issues when possible._
Changed the purple cf logo to orange
## Approach
_How does this change address the problem?_
I changed the clolour
#### Open Questions and Pre-Merge TODOs
- [x] Use github checklists. When solved, check the box and explain the answer.

## Learning
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

#### Blog Posts
- [A Complete Guide to useEffect](https://overreacted.io/a-complete-guide-to-useeffect/) Learn how to use useeffect.

### CODE REVIEW

**Comment by blarfoon** [comment]
There is a `~` in the new filename, can you remove it?

**Comment by Ecorous** [comment]
> 
> 
> There is a `~` in the new filename, can you remove it?

Sure

**Comment by Ecorous** [comment]
> 
> 
> There is a `~` in the new filename, can you remove it?

Nope, that doesn't acutally exist

**Review by machinesmith42 — APPROVED** [review]
Seems good

**Comment by blarfoon** [comment]
There are some conflicts. Could you resolve them so we can get this merged?

**Comment by blarfoon** [comment]
Also as you can see [here](https://github.com/gorilla-devs/GDLauncher/blob/cab34cdfe89373add11cd0b1c1cc29e26e76f77d/src/common/assets/curseforgeIcon.webp~) the filename does have a ~ at the end

**Pull request closed without merging**
