### PR TITLE
ResourcePacks (WIP)

### PR DESCRIPTION
**Pull request by Ladvace**

### CODE REVIEW

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceManager/ResourcePacks.js  11
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceManager/ResourcePacks.js  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceManager/ResourcePacks.js  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceManager/ResourcePacks.js  8
- src/common/modals/InstanceManager/Screenshots.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceManager/ResourcePacks.js  8
- src/common/modals/InstanceManager/Screenshots.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceManager/ResourcePacks.js  9
- src/common/modals/InstanceManager/Screenshots.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
         

Clones added
============
- src/common/modals/InstanceManager/Screenshots.js  1
- src/common/modals/InstanceManager/Mods.js  8
- src/common/modals/InstanceManager/ResourcePacks.js  9
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
         

Clones added
============
- src/common/modals/InstanceManager/Mods.js  3
- src/ui/DragnDropEffect.js  1
- src/common/modals/InstanceManager/ResourcePacks.js  5
- src/common/modals/InstanceManager/Screenshots.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
         

Clones added
============
- src/common/modals/InstanceManager/Mods.js  3
- src/common/modals/InstanceManager/ResourcePacks.js  5
- src/ui/DragnDropEffect.js  1
- src/common/modals/InstanceManager/Screenshots.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
         

Clones added
============
- src/common/modals/InstanceManager/Screenshots.js  1
- src/ui/DragnDropEffect.js  1
- src/common/modals/InstanceManager/ResourcePacks.js  5
- src/common/modals/InstanceManager/Mods.js  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
         

Clones added
============
- src/ui/DragnDropEffect.js  5
- src/common/modals/InstanceManager/ResourcePacks.js  3
- src/common/modals/InstanceManager/Screenshots.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
         

Clones added
============
- src/ui/DragnDropEffect.js  5
- src/common/modals/InstanceManager/ResourcePacks.js  3
- src/common/modals/InstanceManager/Screenshots.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
         

Clones added
============
- src/ui/DragnDropEffect.js  5
- src/common/modals/InstanceManager/ResourcePacks.js  3
- src/common/modals/InstanceManager/Screenshots.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
- src/common/modals/InstanceManager/ResourcePacks.js  4
         

Clones added
============
- src/ui/DragnDropEffect.js  4
- src/common/modals/InstanceManager/ResourcePacks.js  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by blarfoon** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/ui/DragnDropEffect.js  3
- src/common/modals/InstanceManager/ResourcePacks.js  4
         

Clones added
============
- src/ui/DragnDropEffect.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5575864&bid=18280209)

**Comment by furtabs** [comment]
:+1: Would merge but we need to wait for the guy who never comes to watch over the project

Edit: only thing is can we make ResourcesPacks have a space between them.

**Pull request merged**
