### PR TITLE
update selected mods in an instance

### PR DESCRIPTION
**Pull request by Ladvace**

### CODE REVIEW

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/common/modals/ModsUpdater.js  1
         

Clones added
============
- src/common/modals/ModsUpdater.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6082681&bid=19912797)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/common/modals/ModsUpdater.js  1
         

Clones added
============
- src/common/modals/ModsUpdater.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6082681&bid=19912797)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/common/modals/ModsUpdater.js  1
         

Clones added
============
- src/common/modals/ModsUpdater.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6082681&bid=19912797)

**Comment by furtabs** [comment]
Seems fine to me. @killpowa ?

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/common/modals/ModsUpdater.js  1
         

Clones added
============
- src/common/modals/ModsUpdater.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6082681&bid=19912797)

**Comment by blarfoon** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/common/modals/ModsUpdater.js  1
         

Clones added
============
- src/common/modals/ModsUpdater.js  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=6082681&bid=19912797)

**Pull request closed without merging**
