### PR TITLE
Java Manual Setup improvements

### PR DESCRIPTION
**Pull request by Eskaan**
An upgrade for the Manual Java setup page.
- Added a button to check if both Java paths are ok
- Added a little icon and a message to show if the Java path is a valid path
- Already by the Automatic Setup downloaded Java will be asked do delete before being able to set a custom path.

By now, I think you will find a few bugs in the code (please report them to me) so I will continue testing on it.
- [x] Testing on Windows and Mac Completed

Also this is my second pr (#1066), redone all commits on master.
Hope you enjoy these enhancements, Code-Ac.

### CODE REVIEW

**Comment by Eskaan** [comment]
Will test and deliver pictures tomorrow. Good night 😴

**Comment by Eskaan** [comment]
Needs #1062 to work on mac.

**Comment by Eskaan** [comment]
# Changes by this Pull request:
## Style fix for the Java Memory slider in the Settings
Bildschirmfoto 2021-09-25 um 10 04 10 Bildschirmfoto 2021-09-25 um 09 58 56

## A better Manual Setup
- Recognizes if the given folder exists (very helpful when writing the path by yourself)
- Forces you to check the given JRE(s) to ensure a working program
- Lets you also see the `-version` logs for your custom Java
- Added an option to go directly to the logs when in the setup
- Changes the Custom java view in the settings to a way better layout (my thoughts)
- now you can also choose to only set one custom Java, the second one will still update.

**Comment by Ladvace** [comment]
could you solve the conflict with the master branch?

**Comment by Eskaan** [comment]
(There was no conflict)
Edit: Linter hates me whatsoever

**Comment by Ladvace** [comment]
> (There was no conflict) Edit: Linter hates me whatsoever

My bad, not conflicts, eslint

**Comment by Eskaan** [comment]
Yeah was just a memo() as the linter said. Lint checks passed, rest should work out fine.

**Pull request closed without merging**
