### PR TITLE
Crash Handler

### PR DESCRIPTION
**Pull request by Ladvace**

### CODE REVIEW

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceCrashed.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5766786&bid=18874130)

**Comment by killpowa** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceCrashed.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5766786&bid=18874130)

**Comment by blarfoon** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Clones added
============
- src/common/modals/InstanceCrashed.js  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/gorilla-devs/GDLauncher/pullRequest?prid=5766786&bid=18874130)

**Comment by Ladvace** [comment]
@CrankySupertoon why did you commit all that stuff in this pr?

**Pull request closed without merging**
