### PR TITLE
java memory slider (overlapping text) fix

### PR DESCRIPTION
**Pull request by Ladvace**

### CODE REVIEW

**Comment by Eskaan** [comment]
Uhm… Ladvace, you removed the Limitation to max system memory. Probably that’s the problem
Or do you have 32G Ram?

**Comment by Eskaan** [comment]
And, if you want to do that, also do that on the second slider in the Overview.js

**Comment by meponderR** [comment]
This is mostly already fixed by [3a93317](https://github.com/gorilla-devs/GDLauncher/commit/3a93317087790ae86a30b528fec15c7ceb8d6e91).

**Comment by blarfoon** [comment]
Meh, this is a garbage PR tbh

**Pull request closed without merging**
